export const VARIABLE = "VAR";

export const CHANGE_SORTING_TYPE = "CHANGE_SORTING_TYPE";

export const CHANGE_SEARCH_BY = "CHANGE_SEARCH_BY";

export const GET_FILMS_LIST_SEARCH_REQUEST = "GET_FILMS_LIST_SEARCH_REQUEST";
export const GET_FILMS_LIST_SEARCH_SUCCESS = "GET_FILMS_LIST_SEARCH_SUCCESS";
export const GET_FILMS_LIST_SEARCH_FAIL = "GET_FILMS_LIST_SEARCH_FAIL";

export const GET_SAME_GENRE_FILMS_REQUEST = "GET_SAME_GENRE_FILMS_REQUEST";
export const GET_SAME_GENRE_FILMS_SUCCESS = "GET_SAME_GENRE_FILMS_SUCCESS";
export const GET_SAME_GENRE_FILMS_FAIL = "GET_SAME_GENRE_FILMS_FAIL";

export const GET_FILM_DATA_REQUEST = "GET_FILM_DATA_REQUEST";
export const GET_FILM_DATA_SUCCESS = "GET_FILM_DATA_SUCCESS";
export const GET_FILM_DATA_FAIL = "GET_FILM_DATA_FAIL";

export const BASIC_URL = "http://react-cdp-api.herokuapp.com/movies/";