import "./normalize.scss";
import "./base.scss";
import "./logo.scss";
import "./app-footer.scss";
import "./search-controls.scss";
import "./general-search-results.scss";
import "./films-search-result.scss";
import "./film-page.scss";
import "./error-page.scss";